[input]
entrypoint = 0x80000400
# Paths are relative to the location of this config file.
output_func_path = "RecompiledFuncs"
symbols_file_path = "mk64.us.syms.toml"
rom_file_path = "mk64.us.z64"

# Fix return in func_80040C54, possibly handwritten assembly.
[[patches.instruction]]
func = "func_80040C54"
vram = 0x80040C8C
value = 0x00000000 # jr    $ra -> nop

[patches]
ignored = [
"__ll_rem_recomp",
"__ull_divremi_recomp",
"__ull_rem_recomp",
"__ull_div_recomp",
"__ll_div_recomp",
"__ll_mod_recomp",
"__ll_mul_recomp",
"__ull_rshift_recomp",
"__osAiDeviceBusy_recomp",
"__osBlockSum",
"__osCheckId_recomp",
"__osCheckPackId_recomp",
"__osContAddressCrc_recomp",
"__osContDataCrc_recomp",
"__osContGetInitData_recomp",
"__osContRamRead_recomp",
"__osContRamWrite_recomp",
"__osDequeueThread_recomp",
"__osDevMgrMain_recomp",
"__osEepStatus_recomp",
"__osEPiRawWriteIo_recomp",
"__osGetCurrFaultedThread",
"__osGetId_recomp",
"__osIdCheckSum",
"__osInsertTimer_recomp",
"__osLeoInterrupt_recomp",
"__osPackEepReadData_recomp",
"__osPackEepWriteData_recomp",
"__osPackRamReadData_recomp",
"__osPackRamWriteData_recomp",
"__osPackReadData_recomp",
"__osPackRequestData_recomp",
"__osPfsDeclearPage",
"__osPfsGetInitData_recomp",
"__osPfsGetStatus_recomp",
"__osPfsReleasePages",
"__osPfsRequestData_recomp",
"__osPfsRWInode_recomp",
"__osPfsSelectBank_recomp",
"__osPiCreateAccessQueue_recomp",
"__osRepairPackId_recomp",
"__osResetGlobalIntMask_recomp",
"__osSetHWIntrRoutine",
"__osSiCreateAccessQueue_recomp",
"__osSiDeviceBusy_recomp",
"__osSiGetAccess_recomp",
"__osSiRawReadIo_recomp",
"__osSiRawStartDma_recomp",
"__osSiRawWriteIo_recomp",
"__osSiRelAccess_recomp",
"__osSpDeviceBusy_recomp",
"__osSpGetStatus_recomp",
"__osSpRawStartDma_recomp",
"__osSpSetPc_recomp",
"__osSpSetStatus_recomp",
"__osSumcalc",
"__osTimerServicesInit_recomp",
"__osViGetCurrentContext_recomp",
"__osViInit_recomp",
"__osViSwapContext_recomp",
"osAiGetLength_recomp",
"osAiSetFrequency_recomp",
"osAiSetNextBuffer_recomp",
"osEepromLongRead_recomp",
"osEepromLongWrite_recomp",
"osEepromProbe_recomp",
"osEepromRead_recomp",
"osEepromWrite_recomp",
"osEPiRawStartDma_recomp",
"osLeoDiskInit_recomp",
"osPfsAllocateFile_recomp",
"osPfsChecker_recomp",
"osPfsDeleteFile_recomp",
"osPfsFileState_recomp",
"osPfsFindFile_recomp",
"osPfsFreeBlocks_recomp",
"osPfsInit_recomp",
"osPfsIsPlug_recomp",
"osPfsNumFiles_recomp",
"osPfsReadWriteFile_recomp",
"osPiGetCmdQueue_recomp",
"osPiRawReadIo_recomp",
"osSetTime",
"osSpTaskLoad_recomp",
"osSpTaskStartGo_recomp",
"osSpTaskYield_recomp",
"osSpTaskYielded_recomp",
"osSyncPrintf",
"osViBlack_recomp",
"osViSetMode_recomp",
"osViSetSpecialFeatures_recomp",
"osViSwapBuffer_recomp",
"osCreateViManager_recomp",
"osCreateMesgQueue_recomp",
"osCreateThread_recomp",
"osDestroyThread_recomp",
"osGetThreadPri_recomp",
"osGetTime_recomp",
"osInitialize_recomp",
"osJamMesg_recomp",
"osRecvMesg_recomp",
"osSendMesg_recomp",
"osSetEventMesg_recomp",
"osSetThreadPri_recomp",
"osSetTimer_recomp",
"osStartThread_recomp",
"osVirtualToPhysical_recomp",
"osViSetEvent_recomp",
"osYieldThread_recomp",
"__osPiGetAccess_recomp",
"__osPiRelAccess_recomp",
"__osSetTimerIntr_recomp",
"osCreatePiManager_recomp",
"osPiStartDma_recomp",
"osPiRawStartDma_recomp",
"osContInit_recomp",
"osContStartReadData_recomp",
"osContGetReadData_recomp",
"viMgrMain_recomp",
"__osTimerInterrupt_recomp",
# functions markes with UNUSED attribute on mk64 decomp
"func_8001530C",
"func_8001C42C",
"func_80021F50",
"func_8002701C",
"func_80027024",
"func_80028F5C",
"func_8002AE20",
"func_8002AE28",
"func_8002AE30",
"func_8002B8A4",
"func_80033940",
"func_8003DC50",
"func_8003DE4C",
"func_80040E84",
"func_80040EA4",
"func_80041680",
"func_800416AC",
"func_80041A70",
"func_80041F54",
"func_80042000",
"func_800420A8",
"func_8004214C",
"func_800421FC",
"func_800423F0",
"func_8004252C",
"func_80043288",
"func_80043390",
"func_800433F8",
"func_80043460",
"func_80043668",
"func_800436D0",
"func_80043764",
"func_800437F8",
"func_800438C4",
"func_8004398C",
"func_80044AB8",
"func_80045614",
"func_80045738",
"func_80045BBC",
"func_80045C48",
"func_80046030",
"func_800464D0",
"func_80046544",
"func_80046634",
"func_80046720",
"func_80046794",
"func_80046874",
"func_80046954",
"func_80046A68",
"func_80046AD4",
"func_80046B38",
"func_80046B9C",
"func_80046BEC",
"func_80046C3C",
"func_80046C78",
"func_80046CDC",
"func_80046D40",
"func_80046D90",
"func_80046DF4",
"func_80047B20",
"func_80047C28",
"func_80047D40",
"func_80047DCC",
"func_80047EC4",
"func_80047FBC",
"func_80048038",
"func_800481B4",
"func_80048228",
"func_80048330",
"func_800486B0",
"func_80048718",
"func_80048780",
"func_800487DC",
"func_80048844",
"func_800488AC",
"func_80048914",
"func_8004897C",
"func_800489E4",
"func_80048A4C",
"func_80048AB4",
"func_80048B24",
"func_80048B94",
"func_80048BE8",
"func_80048C3C",
"func_80048C90",
"func_80048CEC",
"func_80048D48",
"func_80048DA4",
"func_80048E00",
"func_80048E68",
"func_80048ED0",
"func_80048F38",
"func_80049B9C",
"func_80049E08",
"func_80049E98",
"func_80049F28",
"func_80049FB8",
"func_8004A034",
"func_8004A12C",
"func_8004A1BC",
"func_8004A488",
"func_8004A4FC",
"func_8004A570",
"func_8004A5E4",
"func_8004AA10",
"func_8004AAA0",
"func_8004AB00",
"func_8004AB60",
"func_8004ABC0",
"func_8004AC20",
"func_8004AC80",
"func_8004ACE0",
"func_8004AD2C",
"func_8004AD8C",
"func_8004ADEC",
"func_8004AE4C",
"func_8004AEAC",
"func_8004AF0C",
"func_8004AF6C",
"func_8004AFCC",
"func_8004B02C",
"func_8004B180",
"func_8004B254",
"func_8004B4E8",
"func_8004B554",
"func_8004B5A8",
"func_8004BB34",
"func_8004BD14",
"func_8004C354",
"func_8004C35C",
"func_8004C53C",
"func_8004C91C",
"func_8004CBC0",
"func_8004CC24",
"func_8004CC84",
"func_8004CCB4",
"func_8004CCE4",
"func_8004CD18",
"func_8004CD48",
"func_8004CE8C",
"func_8004CF9C",
"func_8004CFF0",
"func_8004D044",
"func_8004D0CC",
"func_8004D0D4",
"func_8004DAB8",
"func_8004DC34",
"func_8004DC6C",
"func_8004DCA4",
"func_8004DCDC",
"func_8004DD0C",
"func_8004DD44",
"func_8004DD74",
"func_8004DDAC",
"func_8004DDDC",
"func_8004DE04",
"func_8004DE2C",
"func_8004DE54",
"func_8004DE84",
"func_8004DEB4",
"func_8004DEEC",
"func_8004DF24",
"func_8004E238",
"func_8004E3B8",
"func_8004E3C0",
"func_8004E3F4",
"func_8004E430",
"func_8004E464",
"func_8004E498",
"func_8004E500",
"func_8004E534",
"func_8004E568",
"func_8004E59C",
"func_8004E5D8",
"func_8004E604",
"func_800557AC",
"func_80057330",
"func_80057338",
"func_800573BC",
"func_800573C4",
"func_800573CC",
"func_800573D4",
"func_800573DC",
"func_80057708",
"func_80057814",
"func_80057858",
"func_800578B0",
"func_80057908",
"func_80057960",
"func_800579B8",
"func_80057AA8",
"func_80057B14",
"func_80057B80",
"func_80057BEC",
"func_8005DAD0",
"func_80072214",
"func_800722F8",
"func_80072408",
"func_8007271C",
"func_8007274C",
"func_8007281C",
"func_800728B0",
"func_80072974",
"func_80072998",
"func_80072A78",
"func_8007348C",
"func_800734D4",
"func_80073568",
"func_80073570",
"func_8007369C",
"func_800739CC",
"func_80073D68",
"func_80073ED4",
"func_80074014",
"func_800742A8",
"func_800742EC",
"func_80078C68",
"func_8007A884",
"func_8007C49C",
"func_80087258",
"func_800873A4",
"func_80087444",
"func_8008748C",
"func_800874D4",
"func_80087F14",
"func_800880DC",
"func_80088F94",
"func_8008900C",
"func_8008A2CC",
"func_8008A610",
"func_8008A810",
"func_8008A830",
"func_8008A850",
"func_8008A870",
"func_8008ABC0",
"func_8008AC40",
"func_8008ACC0",
"func_8008ACC8",
"func_8008ACD0",
"func_8008ACD8",
"func_8008ADC0",
"func_8008ADC8",
"func_8008AE8C",
"func_8008AE94",
"func_8008B018",
"func_8008B020",
"func_8008B028",
"func_8008B030",
"func_8008B1B4",
"func_8008B1BC",
"func_8008B1C4",
"func_8008B1CC",
"func_8008BEA4",
"func_8008C1B8",
"func_8008C1C0",
"func_800914E0",
"func_800930E4",
"func_80093B70",
"func_80093C88",
"func_80093C90",
"func_8009A6D4",
"func_800A939C",
"func_800B4560",
"func_80282050",
"func_802820F8",
"func_80282200",
"func_802825C8",
"func_802846AC",
"func_80290314",
"func_80295D50",
"func_80297524",
"func_80297944",
"func_8029ABD4",
"func_8029AE14",
"func_802A38AC",
"func_802A40A4",
"func_802A40AC",
"func_802A40B4",
"func_802A40BC",
"func_802A40C4",
"func_802A40CC",
"func_802A40D4",
"func_802A40DC",
"func_802A7D54",
"func_802A8190",
"func_802A81EC",
"func_802A82AC",
"func_802A8348",
"func_802A841C",
"func_802A8844",
"func_802A9AEC",
"func_802B4F60",
"func_802B4FF0",
"func_802B60B4",
"func_802B6214",
"func_802B6374",
"func_802B64B0",
"func_802B68F8",
"func_802B79F0",
"func_802B7B50",
"func_802B7C18",
"func_802B7C6C",
"func_802B7D28",
"func_802B8414",
"func_unnamed",
"func_unnamed1",
"func_unnamed10",
"func_unnamed11",
"func_unnamed12",
"func_unnamed13",
"func_unnamed14",
"func_unnamed15",
"func_unnamed16",
"func_unnamed17",
"func_unnamed18",
"func_unnamed19",
"func_unnamed2",
"func_unnamed20",
"func_unnamed21",
"func_unnamed22",
"func_unnamed23",
"func_unnamed24",
"func_unnamed25",
"func_unnamed26",
"func_unnamed27",
"func_unnamed28",
"func_unnamed29",
"func_unnamed3",
"func_unnamed30",
"func_unnamed31",
"func_unnamed32",
"func_unnamed33",
"func_unnamed34",
"func_unnamed4",
"func_unnamed5",
"func_unnamed6",
"func_unnamed7",
"func_unnamed8",
"func_unnamed9"
]